# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-08 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RewardActivity',
            fields=[
                ('actname', models.CharField(max_length=50)),
                ('actcmake', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('logfile', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RewardRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernum', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=18)),
                ('telnum', models.CharField(max_length=11)),
                ('usedtime', models.DateField()),
                ('hostname', models.CharField(max_length=16)),
                ('itemnam', models.CharField(max_length=50)),
                ('gbkey', models.CharField(max_length=12)),
                ('itemitype', models.CharField(max_length=6)),
                ('addrprov', models.CharField(max_length=20)),
                ('addrcity', models.CharField(max_length=20)),
                ('addrdetail', models.CharField(max_length=200)),
                ('cmake', models.CharField(max_length=50)),
                ('checkflag', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tel2Addr',
            fields=[
                ('telnum', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('addrprov', models.CharField(max_length=20)),
                ('addrcity', models.CharField(max_length=20)),
                ('teloperator', models.CharField(max_length=20)),
                ('areacode', models.CharField(max_length=5)),
                ('postcode', models.CharField(max_length=6)),
            ],
        ),
    ]
